# Generated by Django 4.2.2 on 2023-07-25 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_rename_image_product_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='catalog',
            field=models.ImageField(null=True, upload_to='catalog/', verbose_name='изображение'),
        ),
    ]
