# Generated by Django 4.2.2 on 2023-08-20 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='catalog',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='catalog/', verbose_name='изображение'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='Изображение'),
        ),
    ]
